
name: deploy to prod lambda

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_lambda:
    name: deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: run yarn dist
        uses: borales/actions-yarn@v4
        with:
          cmd: dist

      - name: deploy prod lambda
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: alexa-heads-or-tails
          zip_file: dist.zip
